### PR TITLE
Replace single quotes in message with backticks.

### PR DESCRIPTION
**Pull request by jayckaiser**

### CODE REVIEW

**Comment by jayckaiser** [comment]
When you try to parse the outputted metadata JSON, the following error occurs: `unexpected '`.
This has been resolved by replacing single-quotes with backticks in `util.linearize()`.

After this is resolved, a new error occurs: `Error parsing JSON: missing colon`.
This is due to double-quotes not being escaped properly. I circumvent this by retrieving the "message" field from the retrieved JSON body, instead of the JSON body as a whole.

**Comment by jayckaiser** [comment]
@tomreitz I never moved this out of draft. We should merge this fix as soon as possible to circumvent parsing errors during logging when using the EarthbeamDAG.

**Review by tomreitz — COMMENTED** [review]
@jayckaiser this looks good. I [see that](https://github.com/search?q=repo%3Aedanalytics%2Flightbeam%20linearize&type=code) `delete.py` similarly uses `util.linearize()` for logging... should we also update `delete.py` to extract and log only the `message`, as well as `send.py`?

**Comment by jayckaiser** [comment]
Hey @tomreitz, apologies for never responding here. I think we can revisit deletes logging in the future. Only send-logging makes its way into the Earthbeam logging table, so we should prioritize the fix for this context. I think we'll be reviewing the log output in general in the near-future in order to improve Snowflake-querying.

**Review by tomreitz — APPROVED** [review]

**Pull request merged**
