### PR TITLE
Fix: Validation error message shows the wrong number of records

### PR DESCRIPTION
**Pull request by johncmerfeld**
Classic 0- vs. 1-based indexing issue.

### CODE REVIEW

**Review by tomreitz — CHANGES_REQUESTED** [review]
This looks good, thanks @johncmerfeld.

Would it make sense to also update to 1-based `line_number`s throughout in this PR? so `line_number` &rarr; `line_number + 1` also [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/validate.py#L207), and (for `send`) [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/send.py#L93) and [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/send.py#L107). Jay pointed out some time ago that the reported line numbers are 0-based, and that seems related to your change here.

If you disagree, I'll just go ahead and approve this.

**Comment by johncmerfeld** [comment]
> This looks good, thanks @johncmerfeld.
> 
> Would it make sense to also update to 1-based `line_number`s throughout in this PR? so `line_number` → `line_number + 1` also [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/validate.py#L207), and (for `send`) [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/send.py#L93) and [here](https://github.com/edanalytics/lightbeam/blob/496d9a1bafb0049ee394684ee51df4bedd25691f/lightbeam/send.py#L107). Jay pointed out some time ago that the reported line numbers are 0-based, and that seems related to your change here.
> 
> If you disagree, I'll just go ahead and approve this.

Ah yeah great idea. I'll address those and do a general sniff around

**Comment by johncmerfeld** [comment]
@tomreitz let me know what you think of this approach; aiming for maximal clarity and explicitude

**Review by tomreitz — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
